name: only develop branch

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.74.2'
        extended: true

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - run: gem install asciidoctor

    - name: Run Hugo
      run: |
        alias asciidoctor="asciidoctor --attribute=experimental=true --attribute=icons=font"
        hugo --minify --config ./assets/demo/config.toml --themesDir ../../ --contentDir exampleSite/content -baseURL https://hugo-bootstrap.12px.com/
        
    - name: Rsync Deployments
      id: deploy
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{ secrets.heteml }}
      with:
        flags: '-avzr --delete'
        options: ''
        ssh_options: '-p 2222'
        src: 'public/'
        dest: 'nrm@ssh-nrm.heteml.net:web/hugo-bootstrap.12px.com'
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: '#9CDAF0'
        SLACK_TITLE: Staging URL
        SLACK_MESSAGE: 'https://hugo-bootstrap.12px.com :globe_with_meridians:'
